export const String = {
  Login: "Login",
  Phone_Number: "Phone Number",
  Password: "Password",
  ForgotPassword: "ForgotPassword?",
  Login_Capital: "LOGIN",
  Register: "REGISTER",
  Name: "Name",
  Email_id: "Email Id",
  Id: " Enter Id",
  Confirm_password: "Confirm Password",
  Changed_password: "Changed Password",
  Mobile_number: "Mobile Number",
  Enter_Mail_ID: "Enter your registered email id ",
  Submit: "Submit",
  OTP_Verification: "OTP Verification",
  OTP_Msg: "Enter Your 6 digit varification code sent to your Mail id . ",
  confirm_otp: "Confirm Otp",
  Paytm_number: "Paytm Number",
  GooglePay: "Google Pay Number",
  Login: "Login",
  Phone_Number: "Phone Number",
  Password: "Password",
  ForgotPassword: "ForgotPassword?",
  Login_Capital: "LOGIN",
  Register: "REGISTER",
  Name: "Name",
  Email_id: "Email Id",
  Confirm_password: "Confirm Password",
  Mobile_number: "Mobile Number",
  Enter_Mail_ID: "Enter your registered email id ",
  Submit: "Submit",
  Withdraw: "WITHDRAW",
  Wallet_Balance: "WALLET BALANCE",
  WithdrawCoins: "Withdraw Coins",
  Minimum: "*Minimum withdraw amount is 10 coins",
  Deposit: "DEPOSIT",
  Deposit_Coins: "Deposit Coins",
  Minimum_Deposit: "*Minimum Deposit amount is 10 coins",
  Enter_Amout: "Enter Amount",
  Profile: "Profile",
  Passbook: "PASSBOOK",
  Passbook2: "Passbook",
  ReferralCode: "Referral Code",
  TermsAndConditions: "Terms & Conditions",
  Logout: "Logout",
  ContactUS: "Contact Us",
  Query: "If you have any query ,click on above mail id to mail us.",
  Passbook: "PASSBOOK",
  Transactions: "Transactions",
  Filter: "Filter",
  Close: "Close",
  Apply: "Apply",
  Withdraw_details: "WITHDRAWAL DETAILS",
  Payment_Method: "PAYMENT METHOD",
  Payment_method_text: " Choose your payment method ",
  Refrel_code: "Referral Code",
  Cancle: "Cancel",
  Skip: "Skip",
  Add_new_paytm_wallet: "Add New Paytm Wallet Number",
  Add_new_Goggle: "Add New Goggle Pay  Number",
  Add_UPI_ID: "Add New UPI Id",
  UPI_ID: "UPI ID",
  Add_new_data: "Add New Data",
  Number: "Number",
  Add_new_phone_pe: "Add New Phone Pe  Number",
  Phone_pay_num: "Phone Pe Number",
  ThirdParty: "THIRD-PARTY",
  WithdrawDetails: "Withdrawal Details",
  BankDetails: "Bank Details",
  paytmWallet: "Paytm Wallet",
  GooglePay: "Google Pay Number",
  PhonePe: "Phone Pe",
  UPI: "UPI",
  CashDeposit: "CashDeposit",
  AddNew: "Add New",
  ChooseYourPM: "Choose Your Payment Method",
  BankTransfer: "Bank Transfer",
  other: "Other",
  BankName: "Bank Name",
  AccountHolder: "Account Holder Name",
  AccountNumber: "Account Number",
  IFSC: "IFSC",
  AddYourBankAccount: "Add Your Bank Account",
  AddDetails: "Adding Bank Details is mandatory for processing withdrawals.",
  CashDeposit: " Cash Deposit",
  AddNewCash: " Add New Cash",
  fullname: "Full Name",
  city: "City",
  newPassword: "New Password",
  comfirmPassword: "Comfirm Password",
  enterCoins: "Enter Coins",
  WITHDRAW: "WITHDRAW",
  DEPOSITE: "DEPOSITE",
  THIRDPARTY: "THIRD PARTY",
  Note: "Note",
  Remarks: "Remarks",
  notFound: "No data available between these dates.!!!",
  Enter_bank_password: "Enter details and generate new passwprd...",
  Toatl_balance: "Total Balance",
  Zero: "0",
  IN_WITHDRAW: "IN WITHDRAW",
  IN_DEPOSITE: "IN DEPOSITE",
  DO_YOU_HAVE_ANY_REF_CODE: "Do You Have Any Referral Code.",
  MAKE_A_PAYMENT_OF_COINS_UPLOAD_SS:
    "Make a Payment of coins and upload screenhot",
  MAKE_YOUR_PAYMENT_BELOW: "Make Your payment on the details below",
  BANK_NAME: "Bank Name:",
  ACCOUNT_HOLDER_NAME: "Account Holder Name:",
  ACCOUNT_NUMBER: "Account Number:",
  IFSC: "IFSC:",
  CLICK_HERE_TO_UPLOAD_SCREENSHOT: "Click here to upload payment screenshot",
  PERSON_NAME: "Person Name:",
  PAYTM_ID: "Paytm Id",
  GOOGLE_PAY: "Google Pay Name:",
  GOOGLE_PAY_ID: "Google Pay Id:",
  PHONE_PAY: "Phone Pay Name:",
  PHONE_PAY_ID: "Phone Pay Id:",
  UPI: "UPI Name:",
  UPI_ID: "UPI Id:",
  OTHER_NAME: "Other Name:",
  OTHER_ID: "Other ID:",
  Details: "Details",
  Enter_Details_Create_new_password: "Enter Details & Create new password.",
};
